force-app/main/default/objects/Volunteer_Job__c/Volunteer_Job__c.object-meta.xml
<CustomObject>
    <label>Volunteer Job</label>
    <nameField>
        <label>Volunteer Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Job__c/fields/MinAge__c.field-meta.xml
<CustomField>
    <fullName>MinAge__c</fullName>
    <label>Min Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Volunteer_Job__c/fields/Volunteer_Program__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Volunteer Program</label>
    <referenceTo>Volunteer_Program__c</referenceTo>
    <relationshipLabel>Volunteer Jobs</relationshipLabel>
    <relationshipName>Volunteer_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Program__c/Volunteer_Program__c.object-meta.xml
<CustomObject>
    <label>Volunteer Program</label>
    <nameField>
        <label>Volunteer Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Shift__c/Volunteer_Shift__c.object-meta.xml
<CustomObject>
    <label>Volunteer Shift</label>
    <nameField>
        <displayFormat>SH-{0000}</displayFormat>
        <label>Shift ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Shift__c/fields/Remaining_Slots__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Slots__c</fullName>
    <formula>MaxVolunteers__c - Current_Volunteers__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Slots</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Volunteer_Shift__c/fields/Volunteer_Job__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Job__c</fullName>
    <label>Volunteer Job</label>
    <referenceTo>Volunteer_Job__c</referenceTo>
    <relationshipLabel>Volunteer Shifts</relationshipLabel>
    <relationshipName>Volunteer_Shifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/GetVolunteerShifts.cls
global without sharing class GetVolunteerShifts implements Callable {
            public Object call(String action, Map<String, Object> args) {
                Map<String, Object> input = (Map<String, Object>)args.get('input');
                Map<String, Object> output = (Map<String, Object>)args.get('output');
                Map<String, Object> options = (Map<String, Object>)args.get('options');
                return invokeMethod(action, input, output, options);
            }

            public Boolean invokeMethod (String methodName, Map<String, Object> input, Map<String, Object> output, Map<String, Object> options){
                if(methodName.equals('getShiftOptions')){
                    getShiftOptions(input, output, options);
                }
                return true;
            }

            public void getShiftOptions (Map<String, Object> input, Map<String, Object> output, Map<String, Object> options){
                String programId = (String)input.get('ProgramId');
                List<Volunteer_Shift__c> shifts = [
                    SELECT Id, Name, Volunteer_Job__r.Volunteer_Program__c, location__c, starttime__c, Volunteer_Job__r.Name, 
                    Volunteer_Job__r.minage__c, remaining_slots__c, endtime__c FROM Volunteer_Shift__c
                    WHERE Remaining_Slots__c > 0 AND Volunteer_Job__r.Volunteer_Program__c =: 'a0Pf6000001B3QDEA0' LIMIT 50000
                ];
				List<Map<String, String>> UIoptions = new List<Map<String, String>>();
                for(Volunteer_Shift__c shift: shifts){
                    Map<String,String> tempMap = new Map<String,String>();
                    tempMap.put('value', shift.Volunteer_Job__r.name+' '+shift.starttime__c+' '+shift.endtime__c+' ('+shift.Remaining_Slots__c+' slots)');
					tempMap.put('name',shift.Id);
                    UIoptions.add(tempMap);
                }
                output.put('options', UIoptions);
            }
        }